### ISSUE TITLE
application crash

### ISSUE THREAD

**Issue by tejasverixo** [udacity/and-nd-firebase#8]
I am using Android Studio 2.2.3 - after adding FirebaseUI Auth dependencies. i m getting following error 

// FirebaseUI Auth only
    compile 'com.google.firebase:firebase-auth:10.0.1'
    compile 'com.firebaseui:firebase-ui-auth:1.1.1'

// Error Log
```
02-14 13:39:26.331 25149-25172/com.google.firebase.udacity.friendlychat W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
02-14 13:39:26.354 25149-25149/com.google.firebase.udacity.friendlychat A/FirebaseApp: Firebase API initialization failure.
                                                                                       java.lang.reflect.InvocationTargetException
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                           at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                           at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                                           at android.content.ContentProvider.attachInfo(ContentProvider.java:1696)
                                                                                           at android.content.ContentProvider.attachInfo(ContentProvider.java:1671)
                                                                                           at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                                           at android.app.ActivityThread.installProvider(ActivityThread.java:5084)
                                                                                           at android.app.ActivityThread.installContentProviders(ActivityThread.java:4679)
                                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4619)
                                                                                           at android.app.ActivityThread.access$1500(ActivityThread.java:155)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                                        Caused by: java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.firebase.iid.zzg' (declaration of 'com.google.firebase.iid.zzg' appears in /data/data/com.google.firebase.udacity.friendlychat/files/instant-run/dex/slice-com.google.firebase-firebase-iid-9.0.0_1c9f905059174e9b00c5bfb64f0eaaa6fcac8f15-classes.dex)
                                                                                           at com.google.firebase.iid.zzg.zzeC(Unknown Source)
                                                                                           at com.google.firebase.iid.zzg.<init>(Unknown Source)
                                                                                           at com.google.firebase.iid.zzg.<init>(Unknown Source)
                                                                                           at com.google.firebase.iid.zzd.zzb(Unknown Source)
                                                                                           at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                           at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                                           at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                                                           at android.content.ContentProvider.attachInfo(ContentProvider.java:1696) 
                                                                                           at android.content.ContentProvider.attachInfo(ContentProvider.java:1671) 
                                                                                           at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                                                           at android.app.ActivityThread.installProvider(ActivityThread.java:5084) 
                                                                                           at android.app.ActivityThread.installContentProviders(ActivityThread.java:4679) 
                                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4619) 
                                                                                           at android.app.ActivityThread.access$1500(ActivityThread.java:155) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
02-14 13:39:26.359 25149-25172/com.google.firebase.udacity.friendlychat W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
02-14 13:39:26.371 25149-25172/com.google.firebase.udacity.friendlychat W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
02-14 13:39:26.372 25149-25172/com.google.firebase.udacity.friendlychat W/ResourcesManager: Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
02-14 13:39:26.618 25149-25149/com.google.firebase.udacity.friendlychat A/FirebaseApp: Firebase API initialization failure.
                                                                                       java.lang.reflect.InvocationTargetException
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                           at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                           at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                                           at android.content.ContentProvider.attachInfo(ContentProvider.java:1696)
                                                                                           at android.content.ContentProvider.attachInfo(ContentProvider.java:1671)
                                                                                           at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                                           at android.app.ActivityThread.installProvider(ActivityThread.java:5084)
                                                                                           at android.app.ActivityThread.installContentProviders(ActivityThread.java:4679)
                                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4619)
                                                                                           at android.app.ActivityThread.access$1500(ActivityThread.java:155)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                                        Caused by: java.lang.NoSuchMethodError: No static method zzz(Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzaa; or its super classes (declaration of 'com.google.android.gms.common.internal.zzaa' appears in /data/data/com.google.firebase.udacity.friendlychat/files/instant-run/dex/slice-com.google.android.gms-play-services-basement-10.0.1_5d0a0978ccd15d1602f8bf76ef3dda5116b6fe1a-classes.dex)
                                                                                           at com.google.android.gms.measurement.internal.zzx.zzbd(Unknown Source)
                                                                                           at com.google.android.gms.measurement.AppMeasurement.getInstance(Unknown Source)
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                           at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                                           at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                                                           at android.content.ContentProvider.attachInfo(ContentProvider.java:1696) 
                                                                                           at android.content.ContentProvider.attachInfo(ContentProvider.java:1671) 
                                                                                           at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                                                           at android.app.ActivityThread.installProvider(ActivityThread.java:5084) 
                                                                                           at android.app.ActivityThread.installContentProviders(ActivityThread.java:4679) 
                                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4619) 
                                                                                           at android.app.ActivityThread.access$1500(ActivityThread.java:155) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
02-14 13:39:26.920 25149-25149/com.google.firebase.udacity.friendlychat W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-14 13:39:27.916 25149-25149/com.google.firebase.udacity.friendlychat E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                          Process: com.google.firebase.udacity.friendlychat, PID: 25149
                                                                                          java.lang.IllegalArgumentException: Each provider can only be set once. password was set twice.
                                                                                              at com.firebase.ui.auth.AuthUI$SignInIntentBuilder.setProviders(AuthUI.java:572)
                                                                                              at com.google.firebase.udacity.friendlychat.MainActivity$5.onAuthStateChanged(MainActivity.java:187)
                                                                                              at com.google.firebase.auth.FirebaseAuth$1.run(Unknown Source)
                                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
02-14 13:39:37.605 25149-25172/com.google.firebase.udacity.friendlychat W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
```

As per ref [link](https://stackoverflow.com/questions/41416450/setproviders-method-is-marked-deprecated/41616963#41616963) i had updated code for "setProviders". but with the latest code my application get crashed with above error. 

can someone please help me to solve this issue OR tell me what i am doing wrong?

**Comment by HJagad** [comment]
Getting the same problem, @tejasverixo did you manage to resolve it in the end?

**Comment by Sulaiman90** [comment]
For me, changing the versions worked

compile 'com.google.firebase:firebase-database:10.2.0'
compile 'com.google.firebase:firebase-auth:10.2.0'
compile 'com.firebaseui:firebase-ui-auth:1.2.0'

**Comment by khainl1110** [comment]
I cannot compile with new version, is there another way?

**Comment by PranayAnugurti** [comment]
Just add 
`providers.clear();`
above this
` providers.add(new AuthUI.IdpConfig.Builder(AuthUI.EMAIL_PROVIDER).build());
          providers.add(new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build());
          startActivityForResult(
              AuthUI.getInstance()
                  .createSignInIntentBuilder()
                  .setIsSmartLockEnabled(false)
                  .setProviders(providers)
                  .build(),
              RC_SIGN_IN);`

**Comment by ThadeusAjayi** [comment]
As stated by @Sulaiman90  the snippet for the lessons are made with a version rather earlier than 11.0.X and as such when you compile you would find that there are deprecated methods in the snippet.
@tejasverixo if you must use latest dependency, you have to rebuild your code around the UI Auth in the application.
